name: Dodanie produktu
description: Zgłoś swoją organizację do programu Wyślij.co
title: "[Dodanie produktu]"
labels: ["organizacje", "nowy-produkt"]
assignees: 
  - ivellios

body:
  - type: markdown
    attributes:
      value: |
        Ten formularz pomoże Ci w dodaniu produktu do strony Twojej organizacji w Wyślij.co
  - type: dropdown
    id: nazwa_organizacji
    attributes:
      label: Twoja organizacja
      options:
        - Testowa
    validations:
      required: true
  - type: input
    id: nazwa
    attributes:
      label: Nazwa produktu
    validations:
      required: true
  - type: input
    id: opis
    attributes:
      label: Krótki opis produktu
    validations:
      required: false
  - type: input
    id: link
    attributes:
      label: Link do produktu w sklepie internetowym
    validations:
      required: true
