name: Zgoszenie organizacji
description: Zgłoś swoją organizację do programu Wyślij.co
title: "[Organizacja] Nazwa Twojej Organizacji"
labels: ["organizacje", "nowa-organizacja"]
assignees: 
  - ivellios

body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za zainteresowanie dołączeniem do programu Wyślij.co. Wypełnij poniższe pola informacjami o swojej organizacji, żeby zgłosić ją do programu.
        # Podstawowe informacje
