name: Przetworzenie organizacji

on:
  workflow_dispatch:
    inputs:
      issue_number:
        type: string
        required: true
env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read
  issues: write

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ inputs.issue_number }}

      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'

          echo "${{ fromJson(steps.parse.outputs.payload)['Nazwa Twojej organizacji'] }}"

      - name: Ekstrakcja nazwy zgłoszenia 
        id: name_extraction
        run: |
          echo "GITHUB_ISSUE_TITLE=$(gh issue view ${{ inputs.issue_number }} --repo ${{
          github.repository }} --json title --template '{{.title}}')" >> $GITHUB_OUTPUT

      - name: Aktualizacja nazwy
        env:
          name: ${{ github.event.inputs.NAME }}
          GITHUB_TOKEN: ${{ github.token }}
        if: steps.name_extraction.outputs.GITHUB_ISSUE_TITLE == '[Nowa Organizacja]'
        run: |
          gh issue edit --repo "$GITHUB_REPOSITORY" ${{ inputs.issue_number }} --title "[Nowa Organizacja] ${{ fromJson(steps.parse.outputs.payload)['Nazwa Twojej organizacji'] }}"
