name: Walidacja zmiany plików organizacji

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  yaml-linting:
    name: Walidacja pliku organizacji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure all commits are accessible
      - name: Show changed files
        run: |
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            echo "Initial commit or new branch. Listing all files:"
            git ls-files
          else
            echo "Changed files since previous commit:"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          fi
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: organizations/*.yaml
