name: Walidacja zmiany plików organizacji

on:
  push:
    paths:
      - './organizations/**'
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

permissions:
  contents: read

jobs:

  yaml-linting:
    name: Walidacja pliku organizacji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: organizations/*.yaml
