name: Walidacja zmiany plików organizacji

on:
  push:
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

permissions:
  contents: read

jobs:

  yaml-linting:
    name: Walidacja pliku organizacji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show changed files
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: organizations/*.yaml
